name: CI
on:

  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_PASSWORD: Khusiim@123
        ports: ['5432:5432']

    steps:
      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
